### ISSUE TITLE
[SOLVED] Issue Router. -- ikeh ikeh kimchil

### ISSUE THREAD

**Issue by godamri** [PentagonalProject/ProjectSeventh#1]
iki kabel listrik ngeblank becoz karena router SLIM3 nya bekerja benar.
plz solve. huft

**Comment by pentagonal** [comment]
ihh ihh ihhh ...
**we are sorry for that mister !!**

```
Because Rendang Ala Bambang Makan Bawang is Not Good For Your Body sir ...
So .. Please Keep Going And Reply this issue when your gonna butuh bantuan
```
just itu saja kanan?

**Comment by ammarfaizi2** [comment]
Tek tekan kabel listrik barang opo wie?

**Comment by wichaksono** [comment]
Pils.. ucap 7 kali uler melingker, orang nggelengker...

**Comment by pentagonal** [comment]
English Please!!!
**Because In disini we are harus use english** 
so please not use boso mbulet ok?

**Comment by godamri** [comment]
YU!!!! make issue,
# Eike 

> yang harus solve masalah you??!!!
huft

**Comment by pentagonal** [comment]
**Solved !! DONE please open new issue!**

**Comment by godamri** [comment]
jahat!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ammarfaizi2** [comment]
😂😂😂

**Comment by pentagonal** [comment]
Please deh ihhhhh .. jangan komen lagi ...
You are semua gak peduli sama aku :cry: 
masa udah di mark **[SOLVED]** masih di komen :cry:

**Comment by godamri** [comment]
aku ga bisa lupain kamuuuuuuu
